### ISSUE TITLE
请问不支持整数编码吗？

### ISSUE THREAD

**Issue by cs1317** [Huelse/SEAL-Python#102]
encoder=IntegerEncoder(context)
NameError: name 'IntegerEncoder' is not defined

**Comment by Huelse** [comment]
it has already been removed, since [v3.6.0](https://github.com/microsoft/SEAL/blob/main/CHANGES.md#version-360).

**Comment by cs1317** [comment]
I need to use integers for dense-state operations, so which encoding should I use? Can you give an example?

**Comment by Huelse** [comment]
read the examples before you start, like the [bfv example](https://github.com/microsoft/SEAL/blob/main/native/examples/1_bfv_basics.cpp#L214).

**Comment by cs1317** [comment]
`Plaintext x_plain(uint64_to_hex_string(x));`
What is the corresponding api in python?

**Comment by Huelse** [comment]
https://www.google.com/search?q=python+int+to+hex+string

**Comment by cs1317** [comment]
`query=6`
 `query_plain=Plaintext(hex(query))`
ValueError: unable to parse hex_poly

For the reason of the error, I don't think it can be solved simply by converting the decimal system to the hexadecimal system. For details, please refer to：
[https://github.com/microsoft/SEAL/blob/main/native/src/seal/plaintext.cpp](https://github.com/microsoft/SEAL/blob/main/native/src/seal/plaintext.cpp)

**Comment by Huelse** [comment]
I think you misunderstand what I mean, the `hex()` return value with prefix `0x`, which can not be parsed, there is an auto transfer between the wrapper and the lib, just `x_plain = Plaintext ('6')`.
And you can find a lot of examples in previous branches in this repo or the SEAL repo.
