### ISSUE TITLE
How to calculate Polynomial Multiplication?

### ISSUE THREAD

**Issue by ZJG0** [Huelse/SEAL-Python#105]
**Type**
Usage for help

**Descripe**
a=2x^0+x+4x^6,
b=5x^0+6x,
a*b=10x^0+17x+6x^2+20x^6+36x^7, 
How to complete the above calculation using the this library?

**Comment by Huelse** [comment]
It's same as the native SEAL, the examples may help you.

**Comment by ZJG0** [comment]
I checked `examples` of this library and `seal`, but I don't get the method to directly calculate the coefficient of `a*b`. Could you give me an example?

**Comment by ZJG0** [comment]
I calculated the polynomial multiplication as follow:
```
import seal
parms = seal.EncryptionParameters(seal.scheme_type.bfv)
poly_modulus_degree = 4096
plain_modulus = seal.Modulus(1 << 6)
parms.set_poly_modulus_degree(poly_modulus_degree)
parms.set_coeff_modulus(seal.CoeffModulus.Create(4096, [ 40 ]))
parms.set_plain_modulus(plain_modulus)
context = seal.SEALContext(parms, False)

keygen = seal.KeyGenerator(context)
secret_key = keygen.secret_key()
public_key = keygen.create_public_key()
encryptor = seal.Encryptor(context, public_key)
decryptor = seal.Decryptor(context, secret_key)
evaluator = seal.Evaluator(context)

plain1 = seal.Plaintext("3x^7 + 4x^6 + 1x^1 + 2")
plain2 = seal.Plaintext("10x^5 + 9x^4 + 8x^3 + 7x^2 + 6x^1 + 5")

encrypted_1 = encryptor.encrypt(plain1)
result = evaluator.multiply_plain(encrypted_1, plain2)
decrypted_result = decryptor.decrypt(result)
print(decrypted_result.to_string())
```
The result  is wrong as follow:
```
30x^12 + 1Bx^11 + 3Cx^10 + 35x^9 + 2Ex^8 + 27x^7 + 24x^6 + 29x^5 + 1Ax^4 + 17x^3 + 14x^2 + 11x^1 + A
```

**Comment by Huelse** [comment]
The Plaintext only receives a string (which represents a digit number). I recommend you start from [here](https://github.com/microsoft/SEAL/blob/main/native/examples).

**Comment by ZJG0** [comment]
I refer to this https://github.com/microsoft/SEAL/blob/206648d0e4634e5c61dcf9370676630268290b59/native/tests/seal/evaluator.cpp#L1099.
However, the result is wrong.

**Comment by ZJG0** [comment]
I added the `sec_level_type.none`, however, the result is also wrong. You can try the polynomial multiplication from my example.

**Comment by Huelse** [comment]
I tried your example, the result has no problem. It's coded in hex.

**Comment by ZJG0** [comment]
Thanks! I also found the problem. Additionally, calculating by constructing polynomial strings(Plaintext("3x^7 + 4x^6 + 1x^1 + 2")) is cumbersome.  Is this the only way I can compute polynomial multiplication？
