### ISSUE TITLE
TypeError: cannot pickle 'seal.Ciphertext' object

### ISSUE THREAD

**Issue by ZJG0** [Huelse/SEAL-Python#106]
**Descripe**
I wanted to transfer the ciphertext, but the `seal.Ciphertext` was not serialized and could not transfer. What do I need to do to transmit ciphertext？

**Comment by Huelse** [comment]
use `to_string()`, refer to [serialization](https://github.com/Huelse/SEAL-Python/blob/main/examples/7_serialization.py).

**Comment by ZJG0** [comment]
I have tried the `to_string()` according to the serialization. There is a new problem that recovering the ciphertext from `string` requires the `context`. Thus, I have to serialize the `context` and transfer it to another PC, but how can I recover the `context` from `string`. Additionally, the `context` is not safe if leaked.

**Comment by Huelse** [comment]
Have you carefully read the [7_serialization.py](https://github.com/Huelse/SEAL-Python/blob/main/examples/7_serialization.py#L62)? the EncryptionParameters need to be the same.

**Comment by ZJG0** [comment]
Sure, the reason I'm going to transfer the `context` to the other PC is because I'm going to use the same context for encryption and decryption, which now seems to have to be done with pre-agreed parameters.
