### ISSUE TITLE
Not found the seal lib file, check the `SEAL/build/lib`

### ISSUE THREAD

**Issue by Haonan009** [Huelse/SEAL-Python#108]
**Type**
Problem when setup with python.

**Descripe**
I have built SEAL in my PC, problem occured when I try to run the second command on CMD, which is "python setup.py build_ext -i". It said "Not found the seal lib file, check the `SEAL/build/lib`", although two files of "lib" were contained in my folder. Anyone met the same problem?

**Comment by Haonan009** [comment]
> Have you build the SEAL like [this](https://github.com/Huelse/SEAL-Python#windows)?

Yes, I built SEAL through "VS 17 2022" generator. Should I select the "build" folder  under "SEAL", or the one under "SEAL-Python", problem might occur in the path selection.

**Comment by Huelse** [comment]
Checkout the `SEAL/build/lib/*.lib`.

**Comment by Haonan009** [comment]
> Checkout the `SEAL/build/lib/*.lib`.

It worked, seal was now in my site-packages. But it reported an error that "Cannot find reference 'scheme_type' in 'seal.py" when I ran "seal_helper.py". Please help me figure it.

**Comment by Huelse** [comment]
It haven't install yet, move the `seal.*.pyd` generated file to the examples folder.

**Comment by Haonan009** [comment]
Didn't work, sorry but what do you mean "It haven't install yet".

> It haven't install yet, move the `seal.*.pyd` generated file to the examples folder.

**Comment by Haonan009** [comment]
> It haven't install yet, move the `seal.*.pyd` generated file to the examples folder.

What should I do to install it?

**Comment by Huelse** [comment]
Can you show me your workspace? you don't need to install it as developing.

**Comment by Haonan009** [comment]
Already emailed.

**Comment by Huelse** [comment]
Copy the `seal.cp37...pyd` to yout workdir like `examples` and run the python3.7(py37) in same workdir will be work.

**Comment by Haonan009** [comment]
so if my python version is 3.9, it won;t be compatible？
&nbsp;


张昊楠
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月8日(星期一) 下午4:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Huelse/SEAL-Python] Not found the seal lib file, check the `SEAL/build/lib` (Issue #108)





 
Copy the seal.cp37...pyd to yout workdir like examples and run the python3.7(py37) in same workdir will be work.

**Comment by Haonan009** [comment]
张昊楠
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Huelse/SEAL-Python"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月8日(星期一) 下午4:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Huelse/SEAL-Python] Not found the seal lib file, check the `SEAL/build/lib` (Issue #108)





 
Copy the seal.cp37...pyd to yout workdir like examples and run the python3.7(py37) in same workdir will be work.

**Comment by Huelse** [comment]
Because you build the lib by the Python3.7, not 3.9 or else.

**Comment by Haonan009** [comment]
Still report error, didn't know where went wrong.


张昊楠
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Huelse/SEAL-Python"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月8日(星期一) 下午4:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Huelse/SEAL-Python] Not found the seal lib file, check the `SEAL/build/lib` (Issue #108)





 
Copy the seal.cp37...pyd to yout workdir like examples and run the python3.7(py37) in same workdir will be work.

**Comment by Huelse** [comment]
This kind of basic programing problem I can't help you.

**Comment by Haonan009** [comment]
I did what you told me
&nbsp;


张昊楠
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月8日(星期一) 下午4:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Huelse/SEAL-Python] Not found the seal lib file, check the `SEAL/build/lib` (Issue #108)





 
This kind of basic programing problem I can't help you.

**Comment by Haonan009** [comment]
Sorry, I tried as you said, and it worked in the "examples" folder you've provided, but failed in my own folder whose .py file requied seal.

**Comment by Haonan009** [comment]
#47 met the same question
