### ISSUE TITLE
Multiplication Depth analysis 

### ISSUE THREAD

**Issue by ayushmohod** [Huelse/SEAL-Python#112]
I want to use any on of the scheme and get to know about the multiplication depth for the parameters that are ( n = 8192, q = 2^383-2^33+1, t1 = 1099511922689, and t2 = 1099512004609) i want want to know which scheme i can use and how to create this context for it.

**Comment by Huelse** [comment]
You can use `CoeffModulus.MaxBitCount(poly_modulus_degree)` to get the value, and the sum of `CoeffModulus` should smaller than this, [releated issue](https://github.com/microsoft/SEAL/issues/128).

**Comment by golfus06** [comment]
so for n=8192 there are a particular number of bits of q which we can given and sum up those bit to the q i provided,right?

but how can i give plaintext modulus(t1 and t2) value in ckks scheme?

**Comment by Huelse** [comment]
I'm not sure what you want to know, but the rule is simple.
If you need larger a `MaxBitCount`, you can increase the `poly_modulus_degree`, like n=16384, which means the noise budget will be larger and you can do more multiplication at the same accuracy, but the costs are the evaluate will be slower.
