### ISSUE TITLE
seal-python docs

### ISSUE THREAD

**Issue by lyq199992** [Huelse/SEAL-Python#114]
How can I obtain seal's documents

**Comment by Huelse** [comment]
The [examples](https://github.com/microsoft/SEAL/tree/main/native/examples) and the [header files comments](https://github.com/microsoft/SEAL/tree/main/native/src/seal).

**Comment by lyq199992** [comment]
I would like to ask another question, how to do vector inner product for ciphertext and plaintext after homomorphic encryption. Because the encrypted value seems to have become a string form。Thanks

**Comment by Huelse** [comment]
Sorry for reply late, you can read this example [5_ckks_basics](https://github.com/microsoft/SEAL/blob/main/native/examples/5_ckks_basics.cpp).
