### ISSUE TITLE
IntegerEncoder

### ISSUE THREAD

**Issue by jimin0** [Huelse/SEAL-Python#116]
Hello,

I was trying to use the IntegerEncoder in the SEAL-Python library, but I encountered a NameError. Is IntegerEncoder no longer available for use in the current version of the library? If so, could you please advise on the recommended alternative for integer encoding?

**Comment by Huelse** [comment]
Yes, there is no IntegerEncoder after the SEAL v4, you can use the CKKSEncoder or BatchEncoder, [examples](https://github.com/Huelse/SEAL-Python/tree/main/examples).
