### ISSUE TITLE
为什么样例文件夹中没有ckks方案的例子呢？如何快速上手此库呢？

### ISSUE THREAD

**Issue by lylaiyy** [Huelse/SEAL-Python#117]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Huelse** [comment]
You need some C++ and Python basics, it's easy to get it, and the grammar have something in common.
The ckks example is in matrix_operations: [matrix_transpose_test](https://github.com/Huelse/SEAL-Python/blob/257bcf7986e3e447698a0fd031d470633f899ba0/examples/matrix_operations.py#L271).
Please read all items and codes before you submit the issue.
