### ISSUE TITLE
Encountered problems during setup

### ISSUE THREAD

**Issue by pwl101** [Huelse/SEAL-Python#123]
**Type**
problem

**Descripe**

D:\SEAL-Python>python setup.py build_ext -i
running build_ext
building 'seal' extension
"D:\Visual Studio\VC\Tools\MSVC\14.41.34120\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DVERSION_INFO=4.0.0 -IC:\Users\m1366\AppData\Local\Programs\Python\Python311\include -Ipybind11/include -ISEAL/native/src -ISEAL/build/native/src -IC:\Users\m1366\AppData\Local\Programs\Python\Python311\Lib\site-packages\pybind11\include -IC:\Users\m1366\AppData\Local\Programs\Python\Python311\include -IC:\Users\m1366\AppData\Local\Programs\Python\Python311\Include "-ID:\Visual Studio\VC\Tools\MSVC\14.41.34120\include" "-ID:\Visual Studio\VC\Tools\MSVC\14.41.34120\ATLMFC\include" "-ID:\Visual Studio\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-ID:\Visual Studio\VC\Tools\MSVC\14.41.34120\include" "-ID:\Visual Studio\VC\Tools\MSVC\14.41.34120\ATLMFC\include" "-ID:\Visual Studio\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /EHsc /Tpsrc\wrapper.cpp /Fobuild\temp.win-amd64-cpython-311\Release\src\wrapper.obj /std:c++latest /EHsc /bigobj /std:c++latest
wrapper.cpp
D:\SEAL-Python\pybind11\include\pybind11\detail/type_caster_base.h(482): error C2027: 使用了未定义类型“_frame”
C:\Users\m1366\AppData\Local\Programs\Python\Python311\include\pytypedefs.h(22): note: 参见“_frame”的声明
error: command 'D:\\Visual Studio\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

I encountered the above error while executing the Python setup. py build. ext - i command, and I don't know how to solve it

**Comment by pwl101** [comment]
![Uploading 新建 BMP 图像.png…]()

**Comment by pwl101** [comment]
<img width="1239" alt="新建 BMP 图像" src="https://github.com/user-attachments/assets/6282c0b4-8c43-49f6-bea8-c05d3ec4772d">

**Comment by Huelse** [comment]
delete the `SEAL/build` and run:
```
cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DSEAL_USE_MSGSL=OFF -DSEAL_USE_ZLIB=OFF -DSEAL_USE_ZSTD=OFF
cmake --build build --config Release
```
and copy the `SEAL/build/lib/Release/seal-4.1.lib` to `SEAL/build/lib`.

**Comment by wbaay477** [comment]
Hello, my problem is the same as his. I modified it according to your plan, but the result is still the same.

C:\Users\17581\seal_2\SEAL-Python-src-v4.0.0>python setup.py build_ext -i
running build_ext
building 'seal' extension
"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\HostX86\x64\cl.exe" /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DVERSION_INFO=4.0.0 -IC:\Users\17581\AppData\Local\Programs\Python\Python312\include -Ipybind11/include -ISEAL/native/src -ISEAL/build/native/src -IC:\Users\17581\AppData\Local\Programs\Python\Python312\Lib\site-packages\pybind11\include -IC:\Users\17581\AppData\Local\Programs\Python\Python312\include -IC:\Users\17581\AppData\Local\Programs\Python\Python312\Include "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\ATLMFC\include" "-IC:\Program Files\Microsoft Visual Studio\2022\Community\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22621.0\\cppwinrt" /EHsc /Tpsrc\wrapper.cpp /Fobuild\temp.win-amd64-cpython-312\Release\src\wrapper.obj /std:c++latest /EHsc /bigobj /std:c++latest
wrapper.cpp
C:\Users\17581\seal_2\SEAL-Python-src-v4.0.0\pybind11\include\pybind11\detail/type_caster_base.h(482): error C2027: 使用了未定义类型“_frame”
C:\Users\17581\AppData\Local\Programs\Python\Python312\include\pytypedefs.h(22): note: 参见“_frame”的声明
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.41.34120\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

**Comment by pwl101** [comment]
My problem is with the pybind11 library. I manually downloaded the latest version of the pybind11 library and replaced the old one in the folder, which solved the problem.
