### ISSUE TITLE
can't pickle seal.IntegerEncoder objects

### ISSUE THREAD

**Issue by CarmenLee111** [Huelse/SEAL-Python#15]
Hi, I had some code with the master from before March 30th. And now it complains that 
```python
c = seal.Ciphertext()
c2 = copy.deepcopy(c)
can't pickle seal.IntegerEncoder objects
```
I noticed that the object Ciphertext does not have the __setstate__ and __getstate__ methods anymore (the same with the Plaintext object), which explains why they cannot be pickled. Will it be possible to bring back the serialization? It would be a useful feature to be able to copy the objects. 

Thank you!

**Comment by Huelse** [comment]
The SEAL 3.4.5 does check the context while loading the ciphertext or other keys, which means it needs two parameters as input, so it's hard to work in python pickle. I'm trying to solve this.
https://github.com/microsoft/SEAL/blob/9fc376c19488be2bfd213780ee06789754f4b2c2/native/src/seal/ciphertext.h#L562
but you can save the ciphertext or keys like this:
```
old = Ciphertext()
old.save('path')
...
new = Ciphertext()
new.load(context, 'path')
```

**Comment by CarmenLee111** [comment]
Thank you for the prompt reply! :) 
Does the file name require the specification of file type? I got the following error. 
```python
old = seal.Ciphertext()
old.save('ciphertext')
new = seal.Ciphertext()
new.load(context, 'ciphertext')
RuntimeError: ciphertext data is invalid
```
I was thinking of performing the computation in another process that does not have access to the context or keys but only the encoder and the evaluator. Doesn't it beat the purpose to require the context when copying? What do you think?

**Comment by Huelse** [comment]
Yeah, that's exactly one of what I thought. I can write the context parameters and the ciphertext into one pickle, but my concern is the different parameters between the BFV and CKKS schemes and some cpp code details.
If no problem, don't forget to close this issue.

**Comment by CarmenLee111** [comment]
I played around with the new version and it seems that even with the same context, the keys generated will be different. Therefore it is not possible to recreate the keys and decrypt even with all information about the context. In fact a new context created with the same parameters can be passed on for loading Ciphertext in the next process. A new evaluator generated in the same way works as well. No need to pickle them either. Thank you! :)
