### ISSUE TITLE
errors when setup 

### ISSUE THREAD

**Issue by xiaobing0** [Huelse/SEAL-Python#18]
Please give me some help, I get the seal.lib file, but there are errors when run setup in windows like follow
![image](https://user-images.githubusercontent.com/27495384/79039508-a9ec8500-7c1c-11ea-8b31-ac15e79a2302.png)

**Comment by Huelse** [comment]
try to use the CPython interpreter, a native python interpreter.

**Comment by xiaobing0** [comment]
![image](https://user-images.githubusercontent.com/27495384/79040178-8ed04400-7c21-11ea-95b7-94a69df12693.png)
seems the errors still exist

**Comment by Huelse** [comment]
I'm not sure about your problems, but it seemed that caused by the seal lib.
try to rebuild the seal lib in the release, x64 mod, or change the config `Runtime library` in the VS, which include `/MT /MD, etc` options.
I work well in the VS2017 `/MD` and python3.7.7

**Comment by xiaobing0** [comment]
I reinstall a pure Python 3.7 environment and it works, thanks a lot.
