### ISSUE TITLE
can not find the seal lib

### ISSUE THREAD

**Issue by wmy96** [Huelse/SEAL-Python#26]
hello,  i open the .sln with vs2017, and generate the three solutions successufully ,but when i run the command ' python setup.py build_ext -i ' ,it says  'can not find the seal lib'  ,how to solve it? thank you for you answer!

**Comment by Huelse** [comment]
Make sure you have built the seal.lib successfully
Open the `setup.py`, change the relative path to an absolute path line 19.

**Comment by wmy96** [comment]
oh it is x64,but the real path is Win32,i change it ,but the wrapper.cpp has got error ,it says '
Front end and back end are incompatible (must target the same processor).'

**Comment by Huelse** [comment]
Sorry, this warpper only support for x64 platform, build in ` Release x64` please.

**Comment by wmy96** [comment]
i rebuid it successufully ,the examples can run in pycharm ,but when i run the examples in command ,it says ' no module named seal '

**Comment by Huelse** [comment]
Move the `seal.<version>.pyd to the example folder or `python setup.py install`  which will globally install in the pip

**Comment by wmy96** [comment]
Wa,thank you for your all help,it is nice!!!

**Comment by Lsw-98** [comment]
Hello, I encountered the following problem (unresolved reference 'encryption parameters') when compiling with pychar. Do you know how to solve it?
![Uploading 1609119737(1).png…]()

**Comment by Lsw-98** [comment]
Hello, I encountered the following problem (unresolved reference 'encryption parameters') when compiling with pychar. Do you know how to solve it?
![1609119737(1)](https://user-images.githubusercontent.com/70066311/103184310-8a080900-48f2-11eb-8370-f34df6aa6306.png)
