### ISSUE TITLE
pop_back() on DoubleVector returns None

### ISSUE THREAD

**Issue by adi-ar** [Huelse/SEAL-Python#3]
Hi.
pop_back() method on a DoubleVector object returns None. Is this expected behavior?
If yes, then how can data be cast from DoubleVector to python data types?

Thanks!

**Comment by Huelse** [comment]
I am not sure what you want to do.
you can find `.def("pop_back", &DoubleVector::pop_back)` this line in the wrapper.cpp
this delete the last element in vector like `void function` in cpp

Here is a demo:
```
from seal import *

inputs = DoubleVector()

inputs.push_back(1.1)
inputs.push_back(2.2)
inputs.push_back(3.3)

print(len(inputs))  # 3
print(inputs[0])  #1.1
print(inputs[2])  # 3.3

inputs.pop_back()
print(len(inputs)) # 2
```
There have complete usage examples in the `tests` folder.

**Comment by adi-ar** [comment]
Understood, my bad. Thank you for the response!
