### ISSUE TITLE
Is that possible to serialize key, cipher text into binary string? 

### ISSUE THREAD

**Issue by renziyao** [Huelse/SEAL-Python#33]
Hi, I want to send the cipher text through network. Saving cipher text to a binary file and read it is not convenient. 
Could you please add a function that can serialize cipher text into binary string?

**Comment by Huelse** [comment]
https://github.com/Huelse/SEAL-Python/blob/6dc7bda48b6027a11e04ddb1360f49a83de80bd8/tests/0_data_type.py#L62-L64

just like it.

**Comment by renziyao** [comment]
This can only save cipher text to the file. Is that possible to serialize cipher text to memory?

**Comment by Huelse** [comment]
The [release 3.3.2](https://github.com/Huelse/SEAL-Python/releases/tag/v3.3.2.1) could pickle the ciphertext and the keys objects,
but it's usually large more than the native file.

**Comment by renziyao** [comment]
Thanks. I update SEAL-python and it looks good.
