### ISSUE TITLE
ModuleNotFoundError: No module named 'seal_helper'

### ISSUE THREAD

**Issue by benenzhu** [Huelse/SEAL-Python#38]
![image](https://user-images.githubusercontent.com/18651489/93614052-3a1cca80-fa04-11ea-9db6-11110cb09e11.png)
I successfully build the seal lib using your instructions in Linux, but it returns that error when I run your examples. So how can I find that seal_helper? 
Wish for your reply.

**Comment by Huelse** [comment]
It's in `tests/seal_helper.py`

**Comment by benenzhu** [comment]
Ty that's my fault.
Sth related to the pyCharm path
