### ISSUE TITLE
For windows, when running setup.py it must be inside x64 native tools command prompt and not just the developer command prompt

### ISSUE THREAD

**Issue by andrew-ma** [Huelse/SEAL-Python#41]
For windows, when running setup.py it must be inside x64 native tools command prompt and not just the developer command prompt.

Please put this in the instructions for windows because I spent 2 hours wondering what was causing the linker error
also another issue I had that could be added to the FAQ is that at least c++17 must be selected

**Comment by Huelse** [comment]
Thank for your advice. I will improve it later.
