### ISSUE TITLE
运行案例问题

### ISSUE THREAD

**Issue by gaojunjie03** [Huelse/SEAL-Python#45]
貌似只能是通过cmd命令行方式来运行案例，我用pycharm编辑器跑不了 报没有seal模块。

**Comment by gaojunjie03** [comment]
用编辑器启动案例 怎么解决这个问题呢？

**Comment by Huelse** [comment]
如果是有红色波浪线提示unsolved reference等等, 就去setting里面设置interpreters, 在path里面添加对应的路径, 是包含对应头文件的路径, 不要忘记右边的小按钮去Reload.

原因解释 https://stackoverflow.com/questions/5049842/autocomplete-in-pycharm-for-python-compiled-extensions

**Comment by Lsw-98** [comment]
你好，请问你解决你的问题了吗？我也遇到了相同的问题，但我像StackOverflow中说的那样重新加载模块并没有起效果
，请问你是怎么解决的？（我已经在全局进行安装）
![1609119737(1)](https://user-images.githubusercontent.com/70066311/103184064-10bbe680-48f1-11eb-8de7-18d171b6e15a.png)

**Comment by gaojunjie03** [comment]
> 你好，请问你解决你的问题了吗？我也遇到了相同的问题，但我像StackOverflow中说的那样重新加载模块并没有起效果
> ，请问你是怎么解决的？（我已经在全局进行安装）
> ![1609119737(1)](https://user-images.githubusercontent.com/70066311/103184064-10bbe680-48f1-11eb-8de7-18d171b6e15a.png)

我现在依然是红色的波浪线，但可以用pycharm进行调试。
我是装了python3.7.4 64位的版本，然后pycharm这里配置zhix指向了我安装的python3.7.4的安装目录里的python.exe
![image](https://user-images.githubusercontent.com/30582212/103184154-a6f00c80-48f1-11eb-97bc-40f46e629edf.png)
然后就可以了用pycharm调试了。
我生成出来的pyd文件是：seal.cp37-win_amd64.pyd
这个错误估计每台电脑都不一样。。。我是好使了 不知你那边能不能..

**Comment by Lsw-98** [comment]
我也是可以运行，但红色波浪线还在，我不知道这把pyseal运用到其他模块还可不可以运行。我使用的是python3.8，生成的pyd文件是seal.cp38-win_amd64.pyd。请问你知道seal文件在哪个目录下吗？我想仔细看一下各个模块的功能。我还是个新手，什么都找不到。。。（哭）

**Comment by gaojunjie03** [comment]
> 我也是可以运行，但红色波浪线还在，我不知道这把pyseal运用到其他模块还可不可以运行。我使用的是python3.8，生成的pyd文件是seal.cp38-win_amd64.pyd。请问你知道seal文件在哪个目录下吗？我想仔细看一下各个模块的功能。我还是个新手，什么都找不到。。。（哭）

我也不是很清楚。。我也刚接触在摸索中

**Comment by gaojunjie03** [comment]
> 我也是可以运行，但红色波浪线还在，我不知道这把pyseal运用到其他模块还可不可以运行。我使用的是python3.8，生成的pyd文件是seal.cp38-win_amd64.pyd。请问你知道seal文件在哪个目录下吗？我想仔细看一下各个模块的功能。我还是个新手，什么都找不到。。。（哭）

我也不是很清楚，刚接触不久 还没摸索源码

**Comment by Lsw-98** [comment]
> > 我也是可以运行，但红色波浪线还在，我不知道这把pyseal运用到其他模块还可不可以运行。我使用的是python3.8，生成的pyd文件是seal.cp38-win_amd64.pyd。请问你知道seal文件在哪个目录下吗？我想仔细看一下各个模块的功能。我还是个新手，什么都找不到。。。（哭）
> 
> 我也不是很清楚，刚接触不久 还没摸索源码

好吧，非常感谢你

**Comment by Wuliaxue** [comment]
> 用编辑器启动案例 怎么解决这个问题呢？

请问你的pycharm中有红色波浪线的问题解决了吗？我也遇到了一样的问题，现在很苦恼
