### ISSUE TITLE
py setup.py build_ext -i时报错

### ISSUE THREAD

**Issue by Lsw-98** [Huelse/SEAL-Python#46]
请问我这里除了什么错，是我的pybind11模块有错吗?

<img src="C:\Users\4031\Desktop\捕获.PNG" />

**Comment by Lsw-98** [comment]
![捕获](https://user-images.githubusercontent.com/70066311/103129914-7fbcf380-46d5-11eb-880f-2b57f81e879e.PNG)

**Comment by Huelse** [comment]
`requirements.txt` 里的包有没有安装过？
这个问题在 #44 有讨论过，请先查看之前的issues.

**Comment by Lsw-98** [comment]
安装了，我弄好了。但现在我有一个新问题，这个可不可以安装到我的Anaconda的虚拟环境中？
