### ISSUE TITLE
How to use pyseal in my Anaconda environment

### ISSUE THREAD

**Issue by Lsw-98** [Huelse/SEAL-Python#47]
How to install pyseal in Anaconda
![1608976831(1)](https://user-images.githubusercontent.com/70066311/103149445-6cc52480-47a4-11eb-8c19-9a3e93b6f71a.png)

**Comment by Lsw-98** [comment]
命令我打开可以运行案例，但用pycharm打开显示 Unresolved reference 'seal_helper'

**Comment by Huelse** [comment]
我们并没有在Anaconda尝试过，这个库主要依赖CPython解释器，你可以自行尝试。

seal_helper就在`tests/seal_helper.py`，其更多问题请参考 #45

**Comment by Lsw-98** [comment]
![1608982157(1)](https://user-images.githubusercontent.com/70066311/103150607-bc115200-47b0-11eb-8254-d66e3a7b48cd.png)
我的seal_helper.py显示，请问怎么解决？在问题#45中在path中添加对应头文件的路径是什么意思？

**Comment by Lsw-98** [comment]
![Uploading 1608982794(1).png…]()

**Comment by Lsw-98** [comment]
![Uploading 1608982794(1).png…]()

**Comment by Lsw-98** [comment]
![1608982794(1)](https://user-images.githubusercontent.com/70066311/103150822-b87eca80-47b2-11eb-9498-042d60b52bb7.png)

**Comment by Huelse** [comment]
这个问题已经在 #45 回答过了，在stackoverflow你能找到想要的答案，更多基础编程问题请自行解决。

**Comment by Lsw-98** [comment]
我就是没看懂问题#45，可以详细解释一下吗?

**Comment by Lsw-98** [comment]
seal_helper.py的问题解决了，但seal又出现了这个报错，您帮我看一下这个怎么解决
![1608987436(1)](https://user-images.githubusercontent.com/70066311/103151879-0ef10680-47bd-11eb-89ab-5a505167ba3b.png)

**Comment by Huelse** [comment]
这个就是我上面和你说的 #45 里提到的，在stackoverflow也有解释原因 https://stackoverflow.com/questions/5049842/autocomplete-in-pycharm-for-python-compiled-extensions
如果没全局安装的话需要将`seal.pyd`放到tests或其他运行根目录里

**Comment by Lsw-98** [comment]
我已经使用 py setup.py build_ext -i命令进行全局安装，也将seal<version>.pyd文件放入tests和根目录下，也按照stackoverflow中说明的删除解释器并重新添加，但问题依然没有解决，我不知道我哪里出了问题

**Comment by Lsw-98** [comment]
可能是我的路径出现问题吗？

**Comment by Lsw-98** [comment]
我可以在还有红色波浪线时运行tests文件下的.py文件，但我不知道当我在其他项目中导入seal时会不会出错？

**Comment by Lsw-98** [comment]
另外，我想问一下我去哪里可以找到这些函数，我想知道他们具体是怎么实现的
![1609138923(1)](https://user-images.githubusercontent.com/70066311/103195917-2abfee00-491e-11eb-877f-d17a3b6fa791.png)

**Comment by Huelse** [comment]
抱歉，近期比较忙，不能及时回复，我会在后期闲时集中改进。

一般情况下，红色波浪线只是pycharm找不到对应函数定义，使用cpython解释器（默认）运行成功后即可在整个系统中运行。如果有错误也可能是库代码本身的问题。

这些函数在`SEAL/native/src/seal`中定义，在`src/wrapper.cpp`中绑定函数映射到python

**Comment by Lsw-98** [comment]
谢谢你，我已经很明白了，非常感谢您在百忙之中抽空回答我的问题

**Comment by Wuliaxue** [comment]
> 谢谢你，我已经很明白了，非常感谢您在百忙之中抽空回答我的问题

我也是这个问题，seal未被使用并且代码中有红色波浪线但能运行例子，请问你是怎么解决的

**Comment by Haonan009** [comment]
> > 谢谢你，我已经很明白了，非常感谢您在百忙之中抽空回答我的问题
> 
> 我也是这个问题，seal未被使用并且代码中有红色波浪线但能运行例子，请问你是怎么解决的

遇到同样问题，请问如何解决
