### ISSUE TITLE
build question

### ISSUE THREAD

**Issue by Timkeeper2018** [Huelse/SEAL-Python#5]
In the SEAL-Python step, when I type python3 setup.py build_ext -i. error
wrapper.cpp: 91: 20: error: ‘py :: array_t’ has not been declared
    .def ("numpy", [] (py :: array_t <double> in) {

So I went to download the compiled SO file, but when I opened it with pycharm, some classes showed a red line error, but the operation passed. This has troubled me for a long time, hoping to get a solution.
![20200107102802](https://user-images.githubusercontent.com/45630803/71863640-69223300-3138-11ea-878b-86344c0d79e3.jpg)

**Comment by Huelse** [comment]
@Timkeeper2018 
Sorry, I forget to note it, you need `pip3 install numpy` at first,  version 1.16.5 or else better,
the compiled SO file is an old exmaple, you should recompile it in your system.

**Comment by Timkeeper2018** [comment]
@Huelse  Thanks a lot

**Comment by Timkeeper2018** [comment]
@Huelse  May not have much to do with your project, but still want to take the liberty to ask. The server received the ciphertext, public and relin keys. How does the server calculate the value without context? My current understanding is that if we want to calculate the ciphertext, we need Evaluator, but Evaluator depends on context. I'm very entangled in this one now, thanks in advance

**Comment by Huelse** [comment]
Yes, it needs context first.
The client generate the keys and the ciphertext.
Send the parms, keys(no secret key), ciphertext and the compute progress to the server.
The server load this file to recreate the ciphertext space and compute it.
...
Here is a MS demo [SEAL-Demo](https://github.com/Microsoft/SEAL-Demo)

**Comment by Timkeeper2018** [comment]
@Huelse  There is a small question, how can I import SEAL. When I put the .so file in the project directory, it prompts "No module named 'seal'", but it works when I enter the command python3 XXX.py. Although I see a way to use the ctypes package, but still want to use your from seal import * way, how can I do it?

**Comment by Timkeeper2018** [comment]
![image](https://user-images.githubusercontent.com/45630803/72063117-21f09980-3314-11ea-9db9-773f68df2526.png)

**Comment by Timkeeper2018** [comment]
@Huelse There is a small question, how can I import SEAL. When I put the .so file in the project directory, it prompts "No module named 'seal'", but it works when I enter the command python3 XXX.py. Although I see a way to use the ctypes package, but still want to use your from seal import * way, how can I do it?
![image](https://user-images.githubusercontent.com/45630803/72063216-55332880-3314-11ea-9f81-d74188887188.png)
![image](https://user-images.githubusercontent.com/45630803/72063247-63814480-3314-11ea-8d64-f32a55eeb21d.png)

**Comment by Huelse** [comment]
This project build a dynamic link library which can be recognized and used by the python interpreter (cpython)
as you can see, the .so files name has `cpython`
but this lib can not recognize by the IDE like pycharm
because it's not a 'standard' python lib (python syntax)

**Comment by Timkeeper2018** [comment]
So what compiler do I choose to use code completion? It ’s so uncomfortable to write against the red line haha

**Comment by Huelse** [comment]
I got no way too 😂, maybe you can disable it in the IDE
or import the designated module to make the red line less
Maybe one day, we will build a new real python lib

**Comment by Timkeeper2018** [comment]
haha，bye the way,did you write seal.Ciphertext.save?when i try to save Ciphertext,they told me 'seal.Ciphertext' object has no attribute 'save'.did you how to save it in your program?

**Comment by Timkeeper2018** [comment]
haha，bye the way,did you write seal.Ciphertext.save?when i try to save Ciphertext,they told me 'seal.Ciphertext' object has no attribute 'save'.did you know how to save it in your program?

**Comment by Huelse** [comment]
No, I haven't write the ciphertext.save function binding,
you can imitate the code, in the `wrapper.cpp` line 360
the `save` is in `SEAL/native/src/seal/cipertext.h` line 540
it's easy

**Comment by davidwagnerkc** [comment]
IDE's will support completion if `seal` is installed as a package. https://github.com/Huelse/SEAL-Python/issues/4#issuecomment-563043441

Once it is installed, preferably into a virtual environment, just point the IDE to that Python interpreter for the project you have open up.

**Comment by Huelse** [comment]
@davidwagnerkc Thank you! I will try it later.

**Comment by Huelse** [comment]
@Timkeeper2018 If you don't have any other questions, close this issue please.
