### ISSUE TITLE
clang failed with exit status 1

### ISSUE THREAD

**Issue by Astrmeteor** [Huelse/SEAL-Python#51]
[//]: # Before submitting this issue, make sure you have already searched and still have problems.
**Describe the bug**
After "python3 setup.py build_ext -i", shows as follows:

error: use of undeclared identifier '_subborrow_u64'
error: use of undeclared identifier '_addcarry_u64'
error: use of undeclared identifier '_subborrow_u64'
error: command 'clang' failed with exit status 1

**Device\Environment**
System: macOS Big Sur 11.2.3
Python: 3.8

**Screenshots**
<img width="846" alt="截屏2021-03-24 13 29 41" src="https://user-images.githubusercontent.com/34183048/112255158-01a4c480-8ca5-11eb-9f5a-b3296cfd8fd0.png">

**Comment by Huelse** [comment]
Make sure your environment satisfies the [requirements](https://github.com/microsoft/SEAL#requirements).
And try to rebuild the SEAL with examples `cmake -S . -B build -DSEAL_BUILD_EXAMPLES=ON`, run the examples,
If works well, then build this project again.

**Comment by Astrmeteor** [comment]
All requirements are satisfied. I have already built it on the Linux system. However, I still can not build it on macOS.

**Comment by Huelse** [comment]
Have you run the examples of SEAL?

**Comment by Astrmeteor** [comment]
Could you show me how to run the examples of SEAL? I am not quite familiar with it, sorry about it.

**Comment by Huelse** [comment]
```
cd SEAL
cmake -S . -B build -DSEAL_USE_MSGSL=OFF -DSEAL_USE_ZLIB=OFF -DSEAL_USE_ZSTD=OFF build -DSEAL_BUILD_EXAMPLES=ON
cmake --build build
cd build/bin
./sealexamples
```

**Comment by Astrmeteor** [comment]
Examples worked. But this project still not work. What's the reseaon?

**Comment by Huelse** [comment]
Sorry for reply late,
We think there might be some difference in the big sur with xcode12 which we don't know,
I will try to fix it later.

**Comment by Huelse** [comment]
It seems that this problem has been solved in the latest Xcode command line, may be caused by some unstable traits of clang, you can try again in big sur with new cli now.
