### ISSUE TITLE
cant use the 'python setup.py install' to use the library in other projects

### ISSUE THREAD

**Issue by IradNuriel** [Huelse/SEAL-Python#52]
**Type**
illustrate your original intention.

**Descripe**
I'm trying to use the library in my project, and I found the solution of "python setup.py install" to make it available with pip but it didn't worked.
![image](https://user-images.githubusercontent.com/53393842/112846030-3dc59400-90ae-11eb-999c-9da2bde6b784.png)

**Comment by Huelse** [comment]
Add a suffix `--user` in your command.

**Comment by IradNuriel** [comment]
thanks you very much!
