### ISSUE TITLE
Size of ciphertext in bytes

### ISSUE THREAD

**Issue by pandasamanvaya** [Huelse/SEAL-Python#53]
**Type**
To find the size of ciphertext in bytes

**Describe**
I want to compute the size of ciphertext in bytes. Using sys.getsizeof() on a ciphertext object gives output as 56 bytes which doesn't seem to be the actual size of the ciphertext containing the coefficients of the polynomial. A function for this is available in Microsoft seal library as mentioned in this issue https://github.com/microsoft/SEAL/issues/88. I am wondering if the same is also in this library but seem have had no luck in finding any such method.

**Comment by Huelse** [comment]
Sorry for repy late, you can get the size of a ciphertext like this:
```
cipher = Ciphertext()
...
cipher_size = cipher.size()
# or
ciipher_csize = cipher.size_capacity()
```

**Comment by pandasamanvaya** [comment]
So, cipher.size() outputs 2 whereas seal.Ciphertext class doesn't have any attribute "size_capacity()".

**Comment by Huelse** [comment]
I see, we will commit new attribute for this later.

**Comment by Huelse** [comment]
Now you could try to use `save_size` to get the size of ciphertext or plaintext in bytes.

**Comment by pandasamanvaya** [comment]
I recompiled all the files but it says seal.Ciphertext object has no attribute 'save_size'. However, I was able to perform cipher.save() and cipher.load() without any errors.

**Comment by Huelse** [comment]
It's not an attribute, you should call it as a method, and work well in my environment:
`print(cipher.save_size())`
![](https://i.loli.net/2021/03/30/1CDue9gJBK54OjH.gif)
Can you find the `save_size` in `src/wrapper.cpp` line 216 or `src/wrapper_with_pickle.cpp` line 278?
https://github.com/Huelse/SEAL-Python/blob/c66cef35eb4d2a766521a62e032a6a364d05b742/src/wrapper.cpp#L216
https://github.com/Huelse/SEAL-Python/blob/c66cef35eb4d2a766521a62e032a6a364d05b742/src/wrapper_with_pickle.cpp#L278

**Comment by pandasamanvaya** [comment]
![image](https://user-images.githubusercontent.com/44033666/112955384-fcd88880-915c-11eb-8fcf-bc41f485fc2c.png)
I did the same but it didn't work. I am using Ubuntu 20.04.2 LTS. I also can find save_size() method both in src/wrapper.cpp and src/wrapper_with_pickle.cpp.

**Comment by Huelse** [comment]
What about remove the `build` folder and `.so` files and recompile, or just clone a new repo.
