### ISSUE TITLE
How to use BFV algorithm?

### ISSUE THREAD

**Issue by lidh15** [Huelse/SEAL-Python#54]
最近重新编译安装了一下，现在dir(seal)显示只有BatchEncoder和CKKSEncoder，BFV怎么用呢？原来的IntegerEncoder是BFV吗？现在没了

**Comment by Huelse** [comment]
because of:
https://github.com/microsoft/SEAL/blob/main/CHANGES.md#major-api-changes
refer:
https://github.com/microsoft/SEAL/blob/main/native/examples/1_bfv_basics.cpp
