### ISSUE TITLE
serialization results space cost not acceptable

### ISSUE THREAD

**Issue by lidh15** [Huelse/SEAL-Python#57]
I use BFV encryption to encrypt my numbers and I want to save them, but save function created a binary file with size 128KB for each cipher text!
The raw data is simply a 4Bytes int, the size increased by 32768 times which is not acceptable in my case. 
I didn't use Batch Encoder because I have to do independent addition on each number, can we manipulate numbers in a cipher text by index?
If not, how can I have a smaller serialization of an encrypted number?
I have tried pickle, it gave me 44K bytes, smaller but not really meaningful.

**Comment by Huelse** [comment]
This is a Homomorphic Encryption Library, you can not operate any ciphertext by index, the size of cipher is fixed (influenced by the scheme)
Try to rebuild the project with [zlib or zstandard](https://github.com/microsoft/SEAL/tree/607801221be3f8499d9d8bd93c06f8b201c98e0b#zlib-and-zstandard), if you want a smaller cipher file size, don't forget to write the new api (with zlib or else) in `wrapper.cpp`

**Comment by lidh15** [comment]
ok, I tried to use zlib, but it only cut the size by about 50%, it's not enough for my application, the cipher was still about 10000 fatter than the raw number. I think I need to find another library. Thank you for your help!
