### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by wangbaobaoget** [Huelse/SEAL-Python#59]
![image](https://user-images.githubusercontent.com/55700463/118451050-6883ae80-b727-11eb-950a-50f2b2a44e42.png)

**Comment by Huelse** [comment]
This kind of error, you should understand by yourself, it's may be caused by the low version of cmake.

**Comment by Huelse** [comment]
If no more problem, close this issue please.

**Comment by wangbaobaoget** [comment]
my version of cmake is 3.12.2
