### ISSUE TITLE
git submodule update --init --recursive报错

### ISSUE THREAD

**Issue by Zhengkaixin** [Huelse/SEAL-Python#64]
你好，我在远程服务器linux环境下安装seal，使用`git submodule update --init --recursive`语句时，总是报这个错fatal: clone of 'https://github.com/pybind/pybind11.git' into submodule path '/xxx/xxx/SEAL-Python/pybind11' failed

**Comment by Huelse** [comment]
[git's docs](http://git-scm.com/docs/git-submodule) or `git submodule init && git submodule update`
