### ISSUE TITLE
Docker: => ERROR  fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by yeenjie** [Huelse/SEAL-Python#68]
**Type**
docker build error

**Describe**
When I used docker to build SEAL, an error occurred:
```
 => CACHED [6/8] WORKDIR /python-seal                                      0.0s
 => ERROR [7/8] RUN cd /python-seal &&     git submodule update --init --  0.2s
------
 > [7/8] RUN cd /python-seal &&     git submodule update --init --recursive:
#11 0.228 fatal: not a git repository (or any of the parent directories): .git
```

**Comment by Huelse** [comment]
make sure this [dict](https://github.com/Huelse/SEAL-Python/blob/9846545af8ff26b57ccdd037f75d071d7f047b8e/Dockerfile#L3) has repo in it, you can clone it by yourself.

**Comment by yeenjie** [comment]
Thanks for your reply.

Error is solved.

That is caused by "download the zip." which did not init the repo.
