### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by MarwanNour** [Huelse/SEAL-Python#7]
Is there a way to build this project on a Windows machine? Thank You

**Comment by Huelse** [comment]
It could, you can refer to the SEAL's [doc](https://github.com/microsoft/SEAL) and the pybind11's [doc](https://pybind11.readthedocs.io/en/master/index.html) to compile it in the VS.
And we will write it in few future.

**Comment by Huelse** [comment]
@MarwanNour You can try to compile it in windows now. Thanks fou your support.
