### ISSUE TITLE
Tried to run "python3 setup.py build_ext -i" on fresh Ubuntu 20.04.3 server, it failed to go through.

### ISSUE THREAD

**Issue by NBsyxx** [Huelse/SEAL-Python#75]
[//]: # Before submitting this issue, make sure you have already searched and still have problems.
**Describe the bug**
When I was following the Build-Linux instructions in README.md

`# Run the setup.py
python3 setup.py build_ext -i` 

this step runs forever, the screenshot is attached. Should I try an earlier version of Ubuntu instead of 20?

**Device\Environment**
System: Ubuntu 20.04.3

**Screenshots**
 
![1636673544(1)](https://user-images.githubusercontent.com/36948683/141383735-47db7094-af37-46f3-8fb8-b721fec0e6e7.png)

**Comment by Huelse** [comment]
What's the error?

**Comment by Arman001** [comment]
It seems like it is building perfectly what is really the error, is it not finding the library or what ?

**Comment by NBsyxx** [comment]
> It seems like it is building perfectly what is really the error, is it not finding the library or what ?

![image](https://user-images.githubusercontent.com/36948683/141866306-fe45109a-f0f3-4178-972f-c0bab6c7fbad.png)

after an hour it gives error: 

command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by Huelse** [comment]
This is a common error on vps, you can refer to [stackoverflow](https://stackoverflow.com/questions/30887143/make-j-8-g-internal-compiler-error-killed-program-cc1plus).

**Comment by Mishra1992** [comment]
Hi @Huelse, 
Got the error as in attached file when I run  "python3 setup.py build_ext -i"

<img width="1440" alt="Screenshot 2022-10-28 at 10 15 11 AM" src="https://user-images.githubusercontent.com/53464781/198516727-6380554b-9045-4b02-aac4-02ed4bf4f89b.png">
<img width="1440" alt="Screenshot 2022-10-28 at 10 15 43 AM" src="https://user-images.githubusercontent.com/53464781/198516737-7f4b2083-c5f0-4269-9e29-55a38eafe65e.png">

**Comment by topmaxz** [comment]
@Mishra1992 We haven't support arm arch like M1 now, cause I don't have that device.

**Comment by Huelse** [comment]
@Mishra1992 We haven't support arm arch like M1 now, cause I don't have that device.

**Comment by Mishra1992** [comment]
Hi @Huelse, 
I am not running on M1
<img width="569" alt="Screenshot 2022-10-28 at 11 04 57 AM" src="https://user-images.githubusercontent.com/53464781/198524679-e32737d9-75ae-4af1-b378-ed04c6e98b0b.png">

**Comment by topmaxz** [comment]
@Mishra1992 I just tried in macos 12.6 with python 3.10 and cmake 3.24.2 and it do have some warnings but not like yours, I will try to figure it out later

**Comment by Huelse** [comment]
@Mishra1992  I just tried in macos 12.6 with python 3.10 and cmake 3.24.2 and it does have some warnings but not like yours, I will try to figure it out later.
