### ISSUE TITLE
Can not find the seal lib,

### ISSUE THREAD

**Issue by YuhuiJiang99** [Huelse/SEAL-Python#76]
[//]: # Before submitting this issue, make sure you have already searched and still have problems.
**Describe the bug**
Hi I was trying to run the example code in Colab but experienced this bug: "Can not find the seal lib,
Compile the seal lib first or check the path." As shown in the screenshot, where is the lib file stored in the repo?
![image](https://user-images.githubusercontent.com/87924063/142781178-94d123a6-06bb-484a-8fbf-bbd61d3ce4a6.png)

**Comment by Huelse** [comment]
It will appear in the `SEAL/build` after you build the SEAL lib https://github.com/Huelse/SEAL-Python#windows
