### ISSUE TITLE
ImportError: dynamic module does not define module export function (PyInit_seals)

### ISSUE THREAD

**Issue by liziyu0104** [Huelse/SEAL-Python#77]
**Describe the bug**
when I try to import the seal.so

**Device\Environment**
System: ubuntu 20.0.4 
Python:  3.6.13

I dont know how to fix it, could you help me? Thanks a lot

**Comment by Huelse** [comment]
checkout the [FAQ](https://github.com/Huelse/SEAL-Python#faq) and try to run the demo in examples.

**Comment by liziyu0104** [comment]
thank you! but when I put seal.so in to the examples folder, I can import like "from seal import *" but if I copy this seal.so to my own folder it will raise an error, so I try to use ctypes.CDLL or ctypes.loadlibrary, it can be imported but if call a function, it will raise "udefined symbol + the funciton which I used", I try the method in FAQ, but it doesn't solve. Thank for your help!

**Comment by Huelse** [comment]
We can not know your environment, maybe you can try to use [SEAL 3.3](https://github.com/Huelse/SEAL-Python/tree/3.3.2) or upgrade your python. haming or else is a easy function, like calculating the square difference.

**Comment by liziyu0104** [comment]
OK thank you！
