### ISSUE TITLE
Not defined error in python on Debian11

### ISSUE THREAD

**Issue by Arman001** [Huelse/SEAL-Python#79]
**Type**
Import seal is fine but some functionality is missing

**Describe**
Hi!
I shifted totally from Windows to Linux(Debian11) and while using here seal library, its building of library was successful. I put the library file in ./usr/lib/python3/dist-packages/ . It is importing seal lib fine but error is on other parameters like as below
![image](https://user-images.githubusercontent.com/21517793/149648458-dea941e3-857f-4502-a46d-d1e61a182c1a.png)
Kindly guide me here that what error I am making.
Thanks in advance...

**Comment by Huelse** [comment]
Sorry for replying late, it seems like the IDE problem, or you can try `python3 setup.py install`

**Comment by Arman001** [comment]
Thank you for your reply, you were right about this. It is working perfectly fine in atom though not in vs code. Thanks again for your help.
