### ISSUE TITLE
Encryption and decryption of messages

### ISSUE THREAD

**Issue by Arman001** [Huelse/SEAL-Python#80]
**Type**
Want to know does any one tried encrypting the messages with it?

**Describe**
It is just a question to overall community here that does any one tried encrypting the messages and decrypting them same. I am trying to do that like i did with BFV but approximate results problem does not give back the same message.
Kindly inform me.... Thank you.

**Comment by Huelse** [comment]
It's the hex, you should know about the SEAL lib and its [BFV example](https://github.com/microsoft/SEAL/blob/88bbc51dd684b82a781312ff04abd235c060163e/native/examples/1_bfv_basics.cpp#L214).

**Comment by Arman001** [comment]
Sorry for late reply, I looked at that but I didn't find out any way here. I don't think py seal works takes hex values into encoding. You have any idea about that then kindly share with me......
