### ISSUE TITLE
"EncryptionParameters" is not defined  in VScode on Ubuntu20

### ISSUE THREAD

**Issue by WeiBenqiang** [Huelse/SEAL-Python#86]
I have follow the installation step, and install lib in `site-package`
![image](https://user-images.githubusercontent.com/47845622/162407618-999ea280-2e44-4072-9aa4-5bab0e678d20.png)
I can run all tests, however, in VScode on Ubuntu20, all variable and functions in `seal` are shown below. I cannot use Auto code completion. So how to fix it？ Thank you.
![image](https://user-images.githubusercontent.com/47845622/162407879-8d0c639a-30f1-42e6-9270-5d9187061465.png)

**Comment by Huelse** [comment]
yes, the Pylance can't load a compiled module, you can try to create a stub file for it, or use the PyCharm instead.
