### ISSUE TITLE
Problems of Being Unsecure in Deployment

### ISSUE THREAD

**Issue by Arman001** [Huelse/SEAL-Python#87]
**Type**
Can not find a good way to serialize

**Describe**
May be it is most asked issue here. But still I cant find a good way to serialize parameters here. What if I wan to deploy this in some privacy and security needed environment? 
As currently SEAL-Python supports serializing secret_key, public_key, context and parameters. But we can not share context among others because anything can be created using this.
***
So how we can give evaluator to server without giving up context?
I am a bit new in this field and hope you can kindly clear me on this.
***
**Thank you in advance**

**Comment by Huelse** [comment]
even with the same parms and data, every time the encrypted result is different, like the RSA.

so the parms is a public data anyone can visit it and you need it to create the context, then the evaluator.

just keep the secret_key in your safe local computer.

**Comment by Arman001** [comment]
So that means if we are able to create secret key through keygen with context it will not be useful to decrypt first encrypted text?

**Comment by Huelse** [comment]
of course, it's created by two different public key, you can valid it easily.

**Comment by Arman001** [comment]
**It did checkout.** Thank you very much for your clear and quick response. It helped me a lot and surely I need more reading on this.
Thank you again.
