### ISSUE TITLE
When will SEAL 3.4 be supported?

### ISSUE THREAD

**Issue by zaczanussi** [Huelse/SEAL-Python#9]
Any idea when we can expect support for SEAL version 3.4 or higher? Is this in active development?

Thanks

**Comment by Huelse** [comment]
That's really on schedule, but I haven't begin with it yet.

**Comment by zaczanussi** [comment]
Could I help you? I have experience with SEAL, although none really with python wrappers. But if you could tell me what you needed done I'm sure I could take some of the work off your shoulders?

**Comment by Huelse** [comment]
Yeah, you could. As you can see, if you are familiar with c++ and python, code the wrapper is easy for you. You can refer to the [pybind11's docs](https://pybind11.readthedocs.io/en/master/index.html) and the `sec/wapper.cpp` we have to make it by yourself. I will begin with it soon. If any problems, we can discuss.

**Comment by Huelse** [comment]
You can try to use it in SEAL version 3.4 now, but I haven't finished the pickle function yet, and it may have some bugs.
If no problem, don't forget to close the issue, thanks.

**Comment by zaczanussi** [comment]
Thank you! I will do some testing and let you know!
