### ISSUE TITLE
gsl/span：No such file or directory

### ISSUE THREAD

**Issue by Natruel** [Huelse/SEAL-Python#96]
**Type**
illustrate your original intention.

**Descripe**
When i run the "python3 setup.py build_ext -i", the error occurs:
![Snipaste_2022-09-10_14-46-11](https://user-images.githubusercontent.com/39426020/189472653-07bfbfc8-858d-43af-90de-131cb054f807.png)

**Comment by Huelse** [comment]
[refer to this](https://github.com/Huelse/SEAL-Python#linux), disable the MSGSL and rebuild the SEAL, `cmake -S . -B build -DSEAL_USE_MSGSL=OFF -DSEAL_USE_ZLIB=OFF`
[SEAL_USE_MSGSL](https://github.com/microsoft/SEAL#basic-cmake-options)
