### ISSUE TITLE
CKKS: scale mismatch, but scale and parameters are correct

### ISSUE THREAD

**Issue by Keridos** [Huelse/SEAL-Python#98]
Scale mismatch on trying to do a calculation like x³+y. Both the scales are almost equal to 1 and the parameter ids are also equal. Still a `ValueError: scale mismatch` is thrown. Using git commit hash 25631fb8f99d5288613fe17558c00b692423e418.

Sample code can be found here: https://gist.github.com/Keridos/87e7e577481eb796ee11c18542a8810e

**Comment by Huelse** [comment]
Sorry for replying late, I guess you haven't understood the CKKS scheme and how to work in the SEAL, you can refer to the [5_ckks_basics](https://github.com/microsoft/SEAL/blob/main/native/examples/5_ckks_basics.cpp) to learn.

code:
```
import numpy
from seal import *
import math

parms = EncryptionParameters(scheme_type.ckks)
poly_modulus_degree = 8192
parms.set_poly_modulus_degree(poly_modulus_degree)
parms_id = [60, 40, 40, 60]
parms.set_coeff_modulus(CoeffModulus.Create(poly_modulus_degree, parms_id))
context = SEALContext(parms)
evaluator = Evaluator(context)

keygen = KeyGenerator(context)
public_key = keygen.create_public_key()
relin_keys = keygen.create_relin_keys()

encryptor = Encryptor(context, public_key)
encoder = CKKSEncoder(context)

scale = numpy.power(2., 40)

x = 2.
y = 12.

x_plain = encoder.encode(x, scale)
y_plain = encoder.encode(y, scale)

#  Attempt to calculate x^3 + y
x_encrypted = encryptor.encrypt(x_plain)
y_encrypted = encryptor.encrypt(y_plain)

temp = evaluator.square(x_encrypted)
evaluator.relinearize_inplace(temp, relin_keys)
evaluator.rescale_to_next_inplace(temp)

# evaluator.rescale_to_next_inplace(x_encrypted)
evaluator.mod_switch_to_inplace(x_encrypted, temp.parms_id())
evaluator.multiply_inplace(temp, x_encrypted)
evaluator.relinearize_inplace(temp, relin_keys)
evaluator.rescale_to_next_inplace(temp)
# check the scale
print(math.log2(temp.scale()))
temp.scale(math.pow(2., 40))
# evaluator.rescale_to_next_inplace(y_encrypted)
evaluator.mod_switch_to_inplace(y_encrypted, temp.parms_id())
# Print parameter ids and scale of values. See they seem to be ok
# print(temp.parms_id())
# print(y_encrypted.parms_id())
# print(temp.scale())
# print(y_encrypted.scale())
# This however throws a ValueError: scale mismatch
# should be equal
print(math.log2(temp.scale()), math.log2(y_encrypted.scale()))
temp2 = evaluator.add(temp, y_encrypted)

secret_key = keygen.secret_key()
decryptor = Decryptor(context, secret_key)
plain_result = decryptor.decrypt(temp2)
result = encoder.decode(plain_result)
print(result)
```

**Comment by Keridos** [comment]
Interesting, thanks for the reply. I did miss the part about being able to set the scale freely. Which is referred to as “lying” to Microsoft Seal. The issue can be closed now. Sent from Proton Mail for iOS On Sat, Oct 22, 2022 at 08:26, huelse ***@***.***> wrote:  
Sorry for replying late, I guess you haven't understood the CKKS scheme and how to work in the SEAL, you can refer to the 5_ckks_basics to learn.
code:
import numpy
from seal import *
import math

parms = EncryptionParameters(scheme_type.ckks)
poly_modulus_degree = 8192
parms.set_poly_modulus_degree(poly_modulus_degree)
parms_id = [60, 40, 40, 60]
parms.set_coeff_modulus(CoeffModulus.Create(poly_modulus_degree, parms_id))
context = SEALContext(parms)
evaluator = Evaluator(context)

keygen = KeyGenerator(context)
public_key = keygen.create_public_key()
relin_keys = keygen.create_relin_keys()

encryptor = Encryptor(context, public_key)
encoder = CKKSEncoder(context)

scale = numpy.power(2., 40)

x = 2.
y = 12.

x_plain = encoder.encode(x, scale)
y_plain = encoder.encode(y, scale)

#  Attempt to calculate x^3 + y
x_encrypted = encryptor.encrypt(x_plain)
y_encrypted = encryptor.encrypt(y_plain)

temp = evaluator.square(x_encrypted)
evaluator.relinearize_inplace(temp, relin_keys)
evaluator.rescale_to_next_inplace(temp)

# evaluator.rescale_to_next_inplace(x_encrypted)
evaluator.mod_switch_to_inplace(x_encrypted, temp.parms_id())
evaluator.multiply_inplace(temp, x_encrypted)
evaluator.relinearize_inplace(temp, relin_keys)
evaluator.rescale_to_next_inplace(temp)
# check the scale
print(math.log2(temp.scale()))
temp.scale(math.pow(2., 40))
# evaluator.rescale_to_next_inplace(y_encrypted)
evaluator.mod_switch_to_inplace(y_encrypted, temp.parms_id())
# Print parameter ids and scale of values. See they seem to be ok
# print(temp.parms_id())
# print(y_encrypted.parms_id())
# print(temp.scale())
# print(y_encrypted.scale())
# This however throws a ValueError: scale mismatch
# should be equal
print(math.log2(temp.scale()), math.log2(y_encrypted.scale()))
temp2 = evaluator.add(temp, y_encrypted)

secret_key = keygen.secret_key()
decryptor = Decryptor(context, secret_key)
plain_result = decryptor.decrypt(temp2)
result = encoder.decode(plain_result)
print(result)
