### ISSUE TITLE
is solved this attacks  ?

### ISSUE THREAD

**Issue by pedroelbanquero** [Huelse/SEAL-Python#99]
hello, this paper says this encryption method is broke , this was solved ?

https://arxiv.org/pdf/1906.07127.pdf

V.

**Comment by Huelse** [comment]
Sorry for replying late, as far as I know there is no perfect scheme, you need balance it by yourself.

https://link.springer.com/content/pdf/10.1007/978-3-642-28496-0_4.pdf
